In [1]:
# Numpy >> Numerical Python
# 2005 by Travish Oliphant

In [6]:
import numpy as np

In [7]:
np.__version__

'2.1.3'

In [8]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [8]:
 # Numpy store the data in an array
# An array is a container used to store the data of same data type

In [9]:
# why Numpy
# Computation is fast >> due t array  >> contineous memory location
# mathematical camputation

In [10]:
l = [1, 2, 3, 4, 5]

In [10]:
arr = np.array(l)

In [12]:
arr

array([1. , 2. , 3. , 4. , 5.1])

In [9]:
l = [1, 2, 3, 4, 5.1]
arr = np.array(l)

In [13]:
 arr1 = np.array([[1, 2, 3], [4, 5, 6]])

In [14]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
mat = np.matrix([1, 2, 3, 4]) # matrix is a specialization array, 2 dimension

In [17]:
type(mat)

numpy.matrix

In [18]:
# more way to convert array
l = [1, 2, 3]
np.asarray(l)

array([1, 2, 3])

In [19]:
np.asarray(mat)

array([[1, 2, 3, 4]])

In [20]:
np.asanyarray(mat) #convert the input to an ndarray, but pass ndarray subclass through

matrix([[1, 2, 3, 4]])

In [22]:
t = ([1, 2, 3], [4, 5, 6]) # tuple to array

In [23]:
type(t)

tuple

In [24]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
l = [1, 2, 3, 4, 5]

In [27]:
arr = np.array(l)

In [28]:
arr

array([1, 2, 3, 4, 5])

In [29]:
arr[0] = 500

In [38]:
arr # shalow copy

array([1000,    2,    3,    4,    5])

In [31]:
a = arr.copy()

In [32]:
a

array([500,   2,   3,   4,   5])

In [33]:
arr

array([500,   2,   3,   4,   5])

In [35]:
arr[0] = 1000

In [36]:
arr

array([1000,    2,    3,    4,    5])

In [39]:
a # deep copy

array([500,   2,   3,   4,   5])

In [40]:
# to create an array >> np.array, np.asarray, np.asanyarray, deep copy and shallow copy

In [41]:
# multiple ways to generate array

In [44]:
arr1 = np.fromfunction(lambda i, j : i==j, (3, 3)) # construct an array by executing a function over each coordinate

In [45]:
arr1

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [46]:
arr1.ndim

2

In [48]:
arr1.shape # shape of array

(3, 3)

In [49]:
arr1.size # np of element in array

9

In [50]:
arr2 = np.fromfunction(lambda i, j : i*j, (3, 3))

In [51]:
arr2

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [53]:
for i in range(5):
    print(i)

0
1
2
3
4


In [54]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [55]:
list(i for i in range(5))

[0, 1, 2, 3, 4]

In [56]:
iterable = (i for i in range(5))

In [58]:
np.fromiter(iterable, int) # create a new 1-dimenstion array from an iterable object.

array([0, 1, 2, 3, 4])

In [63]:
np.fromstring('22 23 24', sep = " ") # should be numerical 

array([22., 23., 24.])

In [62]:
# for string character ypu have to use split
string = "Ajay,Vijay,Sanjay"
string1 = string.split(',')
np.array(string1)

array(['Ajay', 'Vijay', 'Sanjay'], dtype='<U6')

In [65]:
# other methed of numpy >> to generate seperate of num
np.arange(1, 10, 0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [66]:
np.linspace(1, 5, 10)  #return evenly  spaced number over a specified interval.
# give me 10 number between 1 and 5 evenly spaced

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [67]:
np.logspace(1, 5, 10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])