In [2]:
import numpy as np

In [3]:
arr1 = np.random.randint(1, 3, (3,3))
arr2 = np.random.randint(1, 3, (3,3))

In [4]:
arr1

array([[2, 1, 2],
       [2, 2, 2],
       [1, 1, 2]], dtype=int32)

In [5]:
arr2

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2]], dtype=int32)

In [6]:
arr1.flatten()#return a copy of the array collapsed into one dimenstion

array([2, 1, 2, 2, 2, 2, 1, 1, 2], dtype=int32)

In [7]:
# expand dimension
arr = np.array([1, 2, 3, 4])

In [8]:
arr.ndim

1

In [11]:
np.expand_dims(arr, axis = 0) # increase the dimension by 1 at provoided

array([[1, 2, 3, 4]])

In [12]:
np.expand_dims(arr, axis = 1).ndim

2

In [13]:
 arr = np.zeros((3, 4))

In [14]:
arr.ndim

2

In [15]:
np.expand_dims(arr, axis=0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [16]:
np.expand_dims(arr, axis=1)

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [17]:
a = np.array([[1], [2], [3]])

In [18]:
a

array([[1],
       [2],
       [3]])

In [20]:
np.squeeze(a) # decrease dimension 

array([1, 2, 3])

In [21]:
np.repeat(a, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [22]:
np.repeat(arr1, 2)

array([2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2], dtype=int32)

In [23]:
np.repeat(arr1, 2, axis=0) 

array([[2, 1, 2],
       [2, 1, 2],
       [2, 2, 2],
       [2, 2, 2],
       [1, 1, 2],
       [1, 1, 2]], dtype=int32)

In [24]:
np.repeat(arr1, 3, axis=1) 

array([[2, 2, 2, 1, 1, 1, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2],
       [1, 1, 1, 1, 1, 1, 2, 2, 2]], dtype=int32)

In [25]:
a

array([[1],
       [2],
       [3]])

In [26]:
np.roll(a, -2)

array([[3],
       [1],
       [2]])

In [31]:
c = np.array([[1,2], [3,4], [5,6], [7,8]])

In [32]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [33]:
np.roll(c, 2)

array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [34]:
np.roll(c, 2, axis=0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [35]:
arr1

array([[2, 1, 2],
       [2, 2, 2],
       [1, 1, 2]], dtype=int32)

In [36]:
arr2

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2]], dtype=int32)

In [37]:
# operations on numpy string array

In [38]:
d = np.array(["pw", "skills"])

In [39]:
d

array(['pw', 'skills'], dtype='<U6')

In [40]:
np.char.upper(d)

array(['PW', 'SKILLS'], dtype='<U6')

In [41]:
np.char.capitalize(d)

array(['Pw', 'Skills'], dtype='<U6')

In [42]:
# mathematic function 

In [43]:
arr1

array([[2, 1, 2],
       [2, 2, 2],
       [1, 1, 2]], dtype=int32)

In [44]:
np.sin(arr1)

array([[0.90929743, 0.84147098, 0.90929743],
       [0.90929743, 0.90929743, 0.90929743],
       [0.84147098, 0.84147098, 0.90929743]])

In [48]:
np.cos(arr1)

array([[-0.41614684,  0.54030231, -0.41614684],
       [-0.41614684, -0.41614684, -0.41614684],
       [ 0.54030231,  0.54030231, -0.41614684]])

In [49]:
np.tan(arr1)

array([[-2.18503986,  1.55740772, -2.18503986],
       [-2.18503986, -2.18503986, -2.18503986],
       [ 1.55740772,  1.55740772, -2.18503986]])

In [50]:
np.power(arr1, 3)

array([[8, 1, 8],
       [8, 8, 8],
       [1, 1, 8]], dtype=int32)

In [51]:
np.max(arr1)

np.int32(2)

In [53]:
np.subtract(arr1, arr2)

array([[ 1,  0,  1],
       [ 1,  1,  1],
       [-1, -1,  0]], dtype=int32)

In [54]:
np.mod(arr1, arr2) # return element with remainder

array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 0]], dtype=int32)

In [55]:
# sort search

e = np.array([5, 6, 1, 2])

In [56]:
e

array([5, 6, 1, 2])

In [57]:
np.sort(e)

array([1, 2, 5, 6])

In [58]:
f = np.array([5, 199, 200, 6, 7, 8])

In [59]:
np.sort(f)

array([  5,   6,   7,   8, 199, 200])

In [61]:
np.searchsorted(f, 170) # find indicates where element should be inserted to maintain order

np.int64(6)

In [62]:
f = np.array([5, 199, 200, 6, 7, 0, 0, 0, 8])

In [63]:
f

array([  5, 199, 200,   6,   7,   0,   0,   0,   8])

In [64]:
np.count_nonzero(f)

6

In [65]:
f[f > 0]

array([  5, 199, 200,   6,   7,   8])

In [67]:
np.where(f>0)

(array([0, 1, 2, 3, 4, 8]),)

In [68]:
np.extract(f>0, f)

array([  5, 199, 200,   6,   7,   8])

In [69]:
f.byteswap()

array([  360287970189639680, -4107282860161892352, -4035225266123964416,
         432345564227567616,   504403158265495552,                    0,
                          0,                    0,   576460752303423488])

In [70]:
# matrix 2d array

import numpy.matlib as nm

In [72]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [73]:
nm.ones((3, 4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [93]:
# numpy linear algebra

arr1 = np.random.randint(1, 10, (3,3))
arr2 = np.random.randint(1, 10, (3,3))

In [94]:
arr1

array([[8, 7, 7],
       [8, 2, 9],
       [2, 5, 3]], dtype=int32)

In [95]:
arr2

array([[6, 5, 6],
       [7, 6, 3],
       [6, 2, 7]], dtype=int32)

In [96]:
arr1 @ arr2

array([[139,  96, 118],
       [116,  70, 117],
       [ 65,  46,  48]], dtype=int32)

In [97]:
np.linalg.det(arr1)

np.float64(-101.99999999999996)

In [98]:
np.linalg.inv(arr1)

array([[ 0.38235294, -0.1372549 , -0.48039216],
       [ 0.05882353, -0.09803922,  0.15686275],
       [-0.35294118,  0.25490196,  0.39215686]])

In [99]:
a = np.array([[2, 3, 5], [5.1, 4, 5], [7, 8, 5]])

In [100]:
a

array([[2. , 3. , 5. ],
       [5.1, 4. , 5. ],
       [7. , 8. , 5. ]])

In [101]:
b = np.array([16, 8, 0])

In [102]:
b

array([16,  8,  0])

In [103]:
np.linalg.solve(a, b)

array([-2.28571429, -0.91428571,  4.66285714])