In [3]:
import numpy as np

In [5]:
a= np.zeros(5) # Return a new array of given shape and type, filled with zero.

In [6]:
a

array([0., 0., 0., 0., 0.])

In [7]:
a.ndim

1

In [8]:
b = np.zeros((3, 4))

In [9]:
b.ndim

2

In [11]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.array([[2, 2, 2], [2, 2, 2]])

array([[2, 2, 2],
       [2, 2, 2]])

In [14]:
arr = np.zeros((3,4))

In [15]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
arr.ndim

2

In [17]:
# 3 dimenstional array 

In [18]:
arr = np.zeros((1, 3, 4))

In [19]:
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [20]:
arr.ndim

3

In [26]:
arr = np.zeros((1, 1, 3, 4))

In [27]:
arr

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [28]:
arr.ndim

4

In [29]:
arr = np.ones((3, 4))

In [30]:
arr.ndim

2

In [31]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [36]:
a = arr * 5

In [37]:
a - 1

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [39]:
np.eye(3) # Return a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [42]:
np.empty((3, 4)) # return a new array of given shape and type, without initialing entries.

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [47]:
# optional >> random module 

import random
random.choice((1, 2, 3, 4, 5))

5

In [49]:
random.choice('ajay')

'j'

In [51]:
random.randrange(1, 10)

7

In [52]:
random.random() # a random no is generated between 0(included) and 1(excluded)

0.6435133699398968

In [53]:
lis = [1, 2, 3, 4, 5]

In [54]:
random.shuffle(lis)

In [55]:
lis

[5, 1, 4, 3, 2]

In [56]:
random.uniform(7, 14)

11.483167153712898

In [58]:
# to have random number related concept in numpy
np.array([])

array([], dtype=float64)

In [60]:
np.random.random_sample()

0.07963255130889801

In [61]:
np.random.random_sample((5, ))

array([0.8539665 , 0.81693353, 0.2675574 , 0.19363985, 0.68106424])

In [62]:
np.random.rand(1)

array([0.41282756])

In [64]:
np.random.rand(2, 3)

array([[0.38360325, 0.01687256, 0.94624867],
       [0.02005968, 0.07022847, 0.73126863]])

In [65]:
np.random.randn(2, 3)

array([[ 1.03562589,  0.16137452,  1.28882306],
       [-0.35714469,  1.16091657, -0.59282664]])

In [67]:
arr = np.random.randint(1, 5, size= (3, 4))

In [68]:
arr.ndim

2

In [69]:
arr.size

12

In [70]:
# reshaping the array

arr

array([[2, 2, 4, 4],
       [4, 3, 3, 2],
       [1, 1, 1, 4]], dtype=int32)

In [72]:
arr1 = arr.reshape(2, 6)

In [73]:
arr1.size

12

In [74]:
# array size will not change, always reshape parameter should be multiplication of original array size

In [76]:
# case when you don't know in reshape what should be the column count.
arr.reshape(4, -1)

array([[2, 2, 4],
       [4, 4, 3],
       [3, 2, 1],
       [1, 1, 4]], dtype=int32)

In [77]:
arr.reshape(2, -100)

array([[2, 2, 4, 4, 4, 3],
       [3, 2, 1, 1, 1, 4]], dtype=int32)

In [80]:
arr.reshape(-2, 3) # you know column count but no row count

array([[2, 2, 4],
       [4, 4, 3],
       [3, 2, 1],
       [1, 1, 4]], dtype=int32)

In [81]:
arr.reshape(2, 2, 3)

array([[[2, 2, 4],
        [4, 4, 3]],

       [[3, 2, 1],
        [1, 1, 4]]], dtype=int32)

In [82]:
arr.reshape(1, 2, 2, 3)

array([[[[2, 2, 4],
         [4, 4, 3]],

        [[3, 2, 1],
         [1, 1, 4]]]], dtype=int32)

In [83]:
arr.reshape(1, 2, 2, 3).ndim

4

In [90]:
# condition on array

arr2 = np.random.randint(1, 10, (5, 6))

In [91]:
arr2.ndim

2

In [92]:
arr3 = np.random.randint(1, 10, (5, 6))

In [95]:
# to access elemnt in array
arr3[0]

array([6, 4, 9, 5, 2, 2], dtype=int32)

In [96]:
arr3

array([[6, 4, 9, 5, 2, 2],
       [3, 9, 2, 1, 5, 5],
       [9, 4, 2, 3, 5, 7],
       [7, 4, 8, 3, 8, 8],
       [8, 6, 1, 2, 4, 1]], dtype=int32)

In [98]:
arr3[0:3]

array([[6, 4, 9, 5, 2, 2],
       [3, 9, 2, 1, 5, 5],
       [9, 4, 2, 3, 5, 7]], dtype=int32)

In [100]:
arr3[0:3, [0, 2]] # 0 to 2nd row and oth and 2nd column

array([[6, 9],
       [3, 2],
       [9, 2]], dtype=int32)

In [103]:
# sliccing on both row and column

In [104]:
arr3

array([[6, 4, 9, 5, 2, 2],
       [3, 9, 2, 1, 5, 5],
       [9, 4, 2, 3, 5, 7],
       [7, 4, 8, 3, 8, 8],
       [8, 6, 1, 2, 4, 1]], dtype=int32)

In [102]:
arr3[0:3, 1:3]

array([[4, 9],
       [9, 2],
       [4, 2]], dtype=int32)

In [105]:
arr3[2:5, 2:4]

array([[2, 3],
       [8, 3],
       [1, 2]], dtype=int32)

In [106]:
arr3[0, [1, 3]]

array([4, 5], dtype=int32)

In [4]:
# mathemetical operatinal on two array
arr1 = np.random.randint(1, 3, (3, 3))
arr2 = np.random.randint(1, 3, (3, 3))

In [108]:
arr1

array([[1, 1, 2],
       [2, 2, 2],
       [1, 1, 2]], dtype=int32)

In [109]:
arr2

array([[1, 2, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [110]:
arr1 + arr2

array([[2, 3, 3],
       [3, 3, 3],
       [2, 2, 3]], dtype=int32)

In [113]:
arr1-arr2 # indexwise element subs

array([[ 0,  1,  1],
       [ 0,  0,  1],
       [ 0, -1,  0]], dtype=int32)

In [114]:
arr1 * arr2

array([[4, 2, 2],
       [4, 1, 2],
       [1, 2, 1]], dtype=int32)

In [115]:
arr1 / arr2

array([[1. , 2. , 2. ],
       [1. , 1. , 2. ],
       [1. , 0.5, 1. ]])

In [116]:
# matric multiplication diffrent from index wise multiplication

In [6]:
arr1 @ arr2 # 1st way to do matric multiplecation

array([[5, 6, 8],
       [5, 7, 9],
       [3, 4, 5]], dtype=int32)

In [7]:
np.dot(arr1, arr2) # ndst way to do matric multiplecation

array([[5, 6, 8],
       [5, 7, 9],
       [3, 4, 5]], dtype=int32)

In [9]:
arr1 / 0 # in python zero division error but numpy no error

C:\Users\HEART\AppData\Local\Temp\ipykernel_14104\842688661.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / 0 # in python zero division error but numpy no error


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [10]:
arr = np.zeros((3, 4))

In [13]:
# Broadcosting 
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [16]:
a = np.array([1, 2, 3, 4])

In [17]:
 arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [20]:
a = np.array([[1, 2, 3, 4]])

In [21]:
# transpose
a.T

array([[1],
       [2],
       [3],
       [4]])

In [22]:
arr1

array([[1, 2, 2],
       [2, 2, 1],
       [1, 1, 1]], dtype=int32)

In [23]:
arr1.T

array([[1, 2, 1],
       [2, 2, 1],
       [2, 1, 1]], dtype=int32)

In [24]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.        ],
       [1.        , 1.        , 1.        ]])

In [25]:
np.log10(arr1)

array([[0.     , 0.30103, 0.30103],
       [0.30103, 0.30103, 0.     ],
       [0.     , 0.     , 0.     ]])

In [26]:
np.exp(arr1)

array([[2.71828183, 7.3890561 , 7.3890561 ],
       [7.3890561 , 7.3890561 , 2.71828183],
       [2.71828183, 2.71828183, 2.71828183]])

In [27]:
np.min(arr1)

np.int32(1)

In [28]:
np.max(arr1
      )

np.int32(2)